
version: '3.8'

services:
  scraper-api:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: gmaps_scraper_api_service # Optional: specify a container name
    ports:
      - "8001:8001" # Map host port 8001 to container port 8001
    restart: unless-stopped # Restart policy
    volumes:
      - .:/app # Mount current directory to /app in container
    working_dir: /app # Set working directory to mounted volume
    networks:
      - shark
    # Optional: Add environment variables if needed for configuration
    # environment:
    #   - HEADLESS_MODE=true
    cpu_shares: 1024 # Add cpu_shares here if not using Swarm mode

# Create the external network first with:
# docker network create shark
networks:
  shark:
    external: true
